from django.urls import path
from .views import (
    home, register, login, job_list, job_detail, post_job, apply_job,
    featured_jobs, user_profile, employer_dashboard, update_application_status,
    my_applications, admin_dashboard, admin_users, admin_jobs, admin_applications,
    admin_delete_job, admin_delete_user, dashboard_login, dashboard_logout,
    submit_contact, subscribe_newsletter, set_job_alert, submit_rating, get_ratings, admin_contacts,
    get_notifications, mark_notifications_read, seeker_profile, update_seeker_profile,
    request_password_reset, confirm_password_reset, increment_job_views, verify_employer,
    submit_site_rating, get_site_ratings, like_site_rating, admin_ratings, job_interest,
    edit_job, delete_job, send_message, get_inbox, get_conversation, unread_message_count, delete_message, delete_conversation, ping_online
)

urlpatterns = [
    path('', home, name='home'),
    path('dashboard/login/', dashboard_login, name='dashboard_login'),
    path('dashboard/logout/', dashboard_logout, name='dashboard_logout'),
    path('dashboard/', admin_dashboard, name='admin_dashboard'),
    path('dashboard/users/', admin_users, name='admin_users'),
    path('dashboard/jobs/', admin_jobs, name='admin_jobs'),
    path('dashboard/applications/', admin_applications, name='admin_applications'),
    path('dashboard/contacts/', admin_contacts, name='admin_contacts'),
    path('dashboard/jobs/delete/<int:job_id>/', admin_delete_job, name='admin_delete_job'),
    path('dashboard/users/delete/<int:user_id>/', admin_delete_user, name='admin_delete_user'),
    path('dashboard/users/verify/<int:user_id>/', verify_employer, name='verify_employer'),
    path('api/auth/register/', register, name='register'),
    path('api/auth/login/', login, name='login'),
    path('api/auth/profile/', user_profile, name='user_profile'),
    path('api/auth/password-reset/', request_password_reset, name='request_password_reset'),
    path('api/auth/password-reset/confirm/', confirm_password_reset, name='confirm_password_reset'),
    path('api/jobs/', job_list, name='job_list'),
    path('api/jobs/featured/', featured_jobs, name='featured_jobs'),
    path('api/jobs/post/', post_job, name='post_job'),
    path('api/jobs/<int:pk>/', job_detail, name='job_detail'),
    path('api/jobs/<int:job_id>/apply/', apply_job, name='apply_job'),
    path('api/jobs/<int:job_id>/view/', increment_job_views, name='increment_job_views'),
    path('api/jobs/<int:job_id>/interest/', job_interest, name='job_interest'),
    path('api/jobs/<int:job_id>/edit/', edit_job, name='edit_job'),
    path('api/jobs/<int:job_id>/delete/', delete_job, name='delete_job'),
    path('api/messages/send/', send_message, name='send_message'),
    path('api/messages/inbox/', get_inbox, name='get_inbox'),
    path('api/messages/conversation/<int:user_id>/', get_conversation, name='get_conversation'),
    path('api/messages/unread/', unread_message_count, name='unread_message_count'),
    path('api/messages/<int:msg_id>/delete/', delete_message, name='delete_message'),
    path('api/messages/conversation/<int:user_id>/delete/', delete_conversation, name='delete_conversation'),
    path('api/ping/', ping_online, name='ping_online'),
    path('api/employer/dashboard/', employer_dashboard, name='employer_dashboard'),
    path('api/employer/applications/<int:app_id>/status/', update_application_status, name='update_application_status'),
    path('api/seeker/applications/', my_applications, name='my_applications'),
    path('api/seeker/profile/<int:user_id>/', seeker_profile, name='seeker_profile'),
    path('api/seeker/profile/update/', update_seeker_profile, name='update_seeker_profile'),
    path('api/notifications/', get_notifications, name='get_notifications'),
    path('api/notifications/read/', mark_notifications_read, name='mark_notifications_read'),
    path('api/contact/', submit_contact, name='submit_contact'),
    path('api/newsletter/', subscribe_newsletter, name='subscribe_newsletter'),
    path('api/job-alert/', set_job_alert, name='set_job_alert'),
    path('api/ratings/', submit_rating, name='submit_rating'),
    path('api/ratings/<int:user_id>/', get_ratings, name='get_ratings'),
    path('api/site-ratings/', get_site_ratings, name='get_site_ratings'),
    path('api/site-ratings/submit/', submit_site_rating, name='submit_site_rating'),
    path('api/site-ratings/<int:rating_id>/like/', like_site_rating, name='like_site_rating'),
    path('dashboard/ratings/', admin_ratings, name='admin_ratings'),
]
