# Generated by Django 4.2.8 on 2026-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_posts_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
